SELECT HISTORY_ID, 
ROUND(DAILY_FEE*(DATEDIFF(END_DATE, START_DATE)+1)*
      (CASE
      WHEN (DATEDIFF(END_DATE, START_DATE)+1 >= 90) THEN 0.85
      WHEN (DATEDIFF(END_DATE, START_DATE)+1 >= 30) THEN 0.92
      WHEN (DATEDIFF(END_DATE, START_DATE)+1 >= 7) THEN 0.95
      ELSE 1
      END),0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE 
WHERE A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;