SELECT A.APNT_NO, C.PT_NAME, C.PT_NO, B.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;